<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-beta.22" />
    <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ecs.Client\src\Ecs.Client.csproj" />
    <ProjectReference Include="..\..\Ticket.Data\src\Ticket.Data.csproj" />
  </ItemGroup>

</Project>
